apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-descheduler
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: kube-system
  project: glueops-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://github.com/kubernetes-sigs/descheduler.git'
    path: charts/descheduler
    targetRevision: v0.33.0
    helm:
      parameters:
        - name: kind
          value: "Deployment"
        - name: replicas
          value: "1"
      values: |-
         {{- toYaml .Values.glueops_node_and_tolerations | nindent 8 }}