apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-cloud-operator
spec:
  destination:
    namespace: glueops-core-terraform-cloud-operator
    name: in-cluster
  project: glueops-core
  source:
    chart: glueops-terraform-cloud-operator
    helm:
      parameters:
      - name: terraform_cloud_api_token
        value: {{ .Values.terraformCloudOperator.terraform_cloud_api_token }}
      {{- if .Values.terraformCloudOperator.cloud.enable.gcp }}
      - name: cloud.enable.gcp
        value: '{{ .Values.terraformCloudOperator.cloud.enable.gcp }}'
      - name: cloud.credentials.gcp.GOOGLE_CREDENTIALS
        value: '{{ .Values.terraformCloudOperator.cloud.credentials.gcp.GOOGLE_CREDENTIALS }}'
      {{- end }}
      {{- if .Values.terraformCloudOperator.cloud.enable.aws }}
      - name: cloud.enable.aws
        value: '{{ .Values.terraformCloudOperator.cloud.enable.aws }}'
      - name: cloud.credentials.aws.AWS_ACCESS_KEY_ID
        value: '{{ .Values.terraformCloudOperator.cloud.credentials.aws.AWS_ACCESS_KEY_ID }}'
      - name: cloud.credentials.aws.AWS_SECRET_ACCESS_KEY
        value: '{{ .Values.terraformCloudOperator.cloud.credentials.aws.AWS_SECRET_ACCESS_KEY }}'
      - name: cloud.credentials.aws.AWS_REGION
        value: '{{ .Values.terraformCloudOperator.cloud.credentials.aws.AWS_REGION }}'
      {{- end }}
      - name: terraform.syncWorkspace.logLevel
        value: debug
    repoURL: https://glueops.github.io/platform-helm-charts
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions:
    - CreateNamespace=true
