apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: {{ index .Values "argo-cd" "glueops" "destination_cluster_for_core_apps" }}
    namespace: glueops-core-internal-ingress-nginx
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: v4.3.0
    helm:
      parameters:
        - name: controller.service.type
          value: {{ index .Values "argo-cd" "glueops" "ingress_controller_service_type" }}
        - name: controller.hostPort.enabled
          value: '{{ index .Values "argo-cd" "glueops" "ingress_controller_host_port_enabled" }}'
      values: |-
        controller:
          electionID: internal-ingress-nginx-leader
          ingressClassByName: true
          ingressClass: internal-ingress-nginx
          ingressClassResource:
            name: internal-ingress-nginx
            enabled: true
            default: false
            controllerValue: "k8s.io/internal-ingress-nginx"
    chart: ingress-nginx
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5